- name: Enable image registry
  import_tasks: deploy_imgreg.yml
  when: ocp4_aio_deploy_type == 'upi' or ocp4_aio_deploy_type == 'ipi'

- name: Enable image registry on SNO Clusters
  import_tasks: deploy_imgreg_sno.yml
  when: ocp4_aio_deploy_type == 'sno'

- name: Wait for image registry to become available on NFS
  pause:
    minutes: 3
  when: ocp4_aio_deploy_nfs or not ocp4_aio_deploy_ocs
